In [3]:
import pandas as pd 
import numpy as np

df=pd.read_csv("C:\\Users\\ADMIN\\Documents\\FP\\Project F\\retail_store_inventory (1)(AutoRecovered).csv")
df.head(7)

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
0,01/01/2022,S001,P0001,Groceries,North,231,127,33.50,20,Rainy,0,29.69,Autumn
1,01/01/2022,S001,P0002,Toys,South,204,150,63.01,20,Sunny,0,66.16,Autumn
2,01/01/2022,S001,P0003,Toys,West,102,65,27.99,10,Sunny,1,31.32,Summer
3,01/01/2022,S001,P0004,Toys,North,469,61,32.72,10,Cloudy,1,34.74,Autumn
4,01/01/2022,S001,P0005,Electronics,East,166,14,73.64,0,Sunny,0,68.95,Summer
5,01/01/2022,S001,P0006,Groceries,South,138,128,76.83,10,Sunny,1,79.35,Winter
6,01/01/2022,S001,P0007,Furniture,East,359,97,34.16,10,Rainy,1,36.55,Winter

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73100 entries, 0 to 73099
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                73100 non-null  object
 1   Store ID            73100 non-null  object
 2   Product ID          73100 non-null  object
 3   Category            73100 non-null  object
 4   Region              73100 non-null  object
 5   Inventory Level     73100 non-null  int64
 6   Units Sold          73100 non-null  int64
 7   Price               73100 non-null  float64
 8   Discount            73100 non-null  int64
 9   Weather Condition   73100 non-null  object
 10  Holiday/Promotion   73100 non-null  int64
 11  Competitor Pricing  73100 non-null  float64
 12  Seasonality         73100 non-null  object
dtypes: float64(2), int64(4), object(7)
memory usage: 7.3+ MB

In [7]:
df.isnull().sum()

Date                  0
Store ID              0
Product ID            0
Category              0
Region                0
Inventory Level       0
Units Sold            0
Price                 0
Discount              0
Weather Condition     0
Holiday/Promotion     0
Competitor Pricing    0
Seasonality           0
dtype: int64

In [9]:
df.describe(include='all')

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Price,Discount,Weather Condition,Holiday/Promotion,Competitor Pricing,Seasonality
count,73100,73100,73100,73100,73100,73100.000000,73100.000000,73100.000000,73100.000000,73100,73100.000000,73100.000000,73100
unique,731,5,20,5,4,NaN,NaN,NaN,NaN,4,NaN,NaN,4
top,01/01/2022,S001,P0001,Furniture,East,NaN,NaN,NaN,NaN,Sunny,NaN,NaN,Spring
freq,100,14620,3655,14699,18349,NaN,NaN,NaN,NaN,18290,NaN,NaN,18317
mean,NaN,NaN,NaN,NaN,NaN,274.469877,136.464870,55.135108,10.009508,NaN,0.497305,55.146077,NaN
std,NaN,NaN,NaN,NaN,NaN,129.949514,108.919406,26.021945,7.083746,NaN,0.499996,26.191408,NaN
min,NaN,NaN,NaN,NaN,NaN,50.000000,0.000000,10.000000,0.000000,NaN,0.000000,5.030000,NaN
25%,NaN,NaN,NaN,NaN,NaN,162.000000,49.000000,32.650000,5.000000,NaN,0.000000,32.680000,NaN
50%,NaN,NaN,NaN,NaN,NaN,273.000000,107.000000,55.050000,10.000000,NaN,0.000000,55.010000,NaN
75%,NaN,NaN,NaN,NaN,NaN,387.000000,203.000000,77.860000,15.000000,NaN,1.000000,77.820000,NaN
max,NaN,NaN,NaN,NaN,NaN,500.000000,499.000000,100.000000,20.000000,NaN,1.000000,104.940000,NaN

In [11]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("/", "_")
)

In [13]:
df.columns

Index(['date', 'store_id', 'product_id', 'category', 'region',
       'inventory_level', 'units_sold', 'price', 'discount',
       'weather_condition', 'holiday_promotion', 'competitor_pricing',
       'seasonality'],
      dtype='object')

In [15]:
df['date'] = pd.to_datetime(df['date'], errors='coerce')
numeric_cols = [
    'inventory_level', 'units_sold', 'price',
    'discount', 'competitor_pricing'
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [17]:
df = df[
    (df['units_sold'] >= 0) &
    (df['inventory_level'] >= 0) &
    (df['price'] > 0)
]

In [19]:
df = df.sort_values(by=['product_id', 'date']).reset_index(drop=True)

In [21]:
from sklearn.preprocessing import LabelEncoder

label_cols = [
    'store_id', 'product_id', 'category',
    'region', 'weather_condition', 'seasonality'
]

for col in label_cols:
    if col in df.columns:
        le = LabelEncoder()
        df[col] = le.fit_transform(df[col])

In [22]:
df.isnull().sum()

date                  44200
store_id                  0
product_id                0
category                  0
region                    0
inventory_level           0
units_sold                0
price                     0
discount                  0
weather_condition         0
holiday_promotion         0
competitor_pricing        0
seasonality               0
dtype: int64

In [23]:
df

,date,store_id,product_id,category,region,inventory_level,units_sold,price,discount,weather_condition,holiday_promotion,competitor_pricing,seasonality
0,2022-01-01,0,0,3,1,231,127,33.50,20,1,0,29.69,0
1,2022-01-01,1,0,3,2,343,104,32.80,20,3,1,30.78,1
2,2022-01-01,2,0,4,2,241,147,67.21,5,3,1,67.39,2
3,2022-01-01,3,0,4,2,477,271,15.62,15,3,0,16.09,3
4,2022-01-01,4,0,4,3,111,77,70.33,10,0,0,70.29,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
73095,NaT,0,19,4,3,119,37,62.97,0,2,1,62.94,1
73096,NaT,1,19,2,2,448,158,88.52,10,0,1,92.88,2
73097,NaT,2,19,4,0,116,17,98.98,20,2,1,100.71,1
73098,NaT,3,19,2,2,177,139,84.29,0,3,0,80.33,1
73099,NaT,4,19,2,0,64,40,90.79,5,2,1,91.67,3

In [24]:
df_raw = pd.read_csv("C:\\Users\\ADMIN\\Downloads\\retail_store_inventory (1).csv")
df_raw['Date'].isnull().sum()
df_raw.head()
df_raw.loc[1440:1460, 'Date']

1440    15/01/2022
1441    15/01/2022
1442    15/01/2022
1443    15/01/2022
1444    15/01/2022
1445    15/01/2022
1446    15/01/2022
1447    15/01/2022
1448    15/01/2022
1449    15/01/2022
1450    15/01/2022
1451    15/01/2022
1452    15/01/2022
1453    15/01/2022
1454    15/01/2022
1455    15/01/2022
1456    15/01/2022
1457    15/01/2022
1458    15/01/2022
1459    15/01/2022
1460    15/01/2022
Name: Date, dtype: object

In [25]:
df['date'] = pd.to_datetime(df_raw['Date'], format='%d/%m/%Y')

In [26]:
df.isnull().sum()

date                  0
store_id              0
product_id            0
category              0
region                0
inventory_level       0
units_sold            0
price                 0
discount              0
weather_condition     0
holiday_promotion     0
competitor_pricing    0
seasonality           0
dtype: int64

In [28]:
df

,date,store_id,product_id,category,region,inventory_level,units_sold,price,discount,weather_condition,holiday_promotion,competitor_pricing,seasonality
0,2022-01-01,0,0,3,1,231,127,33.50,20,1,0,29.69,0
1,2022-01-01,1,0,3,2,343,104,32.80,20,3,1,30.78,1
2,2022-01-01,2,0,4,2,241,147,67.21,5,3,1,67.39,2
3,2022-01-01,3,0,4,2,477,271,15.62,15,3,0,16.09,3
4,2022-01-01,4,0,4,3,111,77,70.33,10,0,0,70.29,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
73095,2024-01-01,0,19,4,3,119,37,62.97,0,2,1,62.94,1
73096,2024-01-01,1,19,2,2,448,158,88.52,10,0,1,92.88,2
73097,2024-01-01,2,19,4,0,116,17,98.98,20,2,1,100.71,1
73098,2024-01-01,3,19,2,2,177,139,84.29,0,3,0,80.33,1
73099,2024-01-01,4,19,2,0,64,40,90.79,5,2,1,91.67,3

In [31]:
df = df.sort_values('date').reset_index(drop=True)

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73100 entries, 0 to 73099
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   date                73100 non-null  datetime64[ns]
 1   store_id            73100 non-null  int32
 2   product_id          73100 non-null  int32
 3   category            73100 non-null  int32
 4   region              73100 non-null  int32
 5   inventory_level     73100 non-null  int64
 6   units_sold          73100 non-null  int64
 7   price               73100 non-null  float64
 8   discount            73100 non-null  int64
 9   weather_condition   73100 non-null  int32
 10  holiday_promotion   73100 non-null  int64
 11  competitor_pricing  73100 non-null  float64
 12  seasonality         73100 non-null  int32
dtypes: datetime64[ns](1), float64(2), int32(6), int64(4)
memory usage: 5.6 MB

In [38]:
df.to_csv("cleaned_retail_dataset_date.csv", index=False)
print("Saved as cleaned_retail_dataset_date.csv ")

Saved as cleaned_retail_dataset_date.csv

In [40]:
df_feat = df.sort_values(['store_id','product_id','date']).reset_index(drop=True)

df_feat['lag_1'] = df_feat.groupby(['store_id','product_id'])['units_sold'].shift(1)
df_feat['lag_7'] = df_feat.groupby(['store_id','product_id'])['units_sold'].shift(7)

df_feat['roll_mean_7'] = (
    df_feat.groupby(['store_id','product_id'])['units_sold']
    .shift(1).rolling(7).mean()
)

df_feat['roll_mean_14'] = (
    df_feat.groupby(['store_id','product_id'])['units_sold']
    .shift(1).rolling(14).mean()
)

df_feat['roll_std_7'] = (
    df_feat.groupby(['store_id','product_id'])['units_sold']
    .shift(1).rolling(7).std()
)

# Time features
df_feat['month'] = df_feat['date'].dt.month
df_feat['day_of_week'] = df_feat['date'].dt.dayofweek
df_feat['day'] = df_feat['date'].dt.day

# Remove rows that don't have enough history (because lag/rolling will create NaNs at the start)
df_feat = df_feat.dropna().reset_index(drop=True)
print("After lag features, rows:", len(df_feat))

After lag features, rows: 71700

In [41]:
df_feat.columns

Index(['date', 'store_id', 'product_id', 'category', 'region',
       'inventory_level', 'units_sold', 'price', 'discount',
       'weather_condition', 'holiday_promotion', 'competitor_pricing',
       'seasonality', 'lag_1', 'lag_7', 'roll_mean_7', 'roll_mean_14',
       'roll_std_7', 'month', 'day_of_week', 'day'],
      dtype='object')

In [45]:
drop_cols = ['date']
X = df_feat.drop(columns=drop_cols + ['units_sold'], errors='ignore')
y = df_feat['units_sold']

In [47]:
split_index = int(len(df_feat) * 0.8)

X_train = X.iloc[:split_index]
X_test  = X.iloc[split_index:]

y_train = y.iloc[:split_index]
y_test  = y.iloc[split_index:]

In [49]:
from xgboost import XGBRegressor

model = XGBRegressor(
    n_estimators=600,
    learning_rate=0.05,
    max_depth=8,
    subsample=0.9,
    colsample_bytree=0.9,
    random_state=42
)

model.fit(X_train, y_train)
print("Model trained ")

Model trained

In [50]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

y_pred = model.predict(X_test)

print("MAE:", mean_absolute_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R2:", r2_score(y_test, y_pred))

MAE: 70.33372497558594
RMSE: 90.51416174589752
R2: 0.3155778646469116

In [51]:
import pandas as pd

importance = pd.DataFrame({
    'feature': X_train.columns,
    'importance': model.feature_importances_
}).sort_values(by='importance', ascending=False)

importance.head(10)

               feature  importance
4      inventory_level    0.251264
15          roll_std_7    0.049513
9   competitor_pricing    0.049257
13         roll_mean_7    0.048234
14        roll_mean_14    0.048127
11               lag_1    0.048113
12               lag_7    0.048026
18                 day    0.046661
16               month    0.045751
5                price    0.044403

In [52]:
X_no_inventory = X.drop(columns=['inventory_level'])

split_index = int(len(X_no_inventory) * 0.8)

X_train = X_no_inventory.iloc[:split_index]
X_test  = X_no_inventory.iloc[split_index:]
y_train = y.iloc[:split_index]
y_test  = y.iloc[split_index:]

_ = model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import r2_score
print("R2:", r2_score(y_test, y_pred))

R2: -0.04223525524139404

In [53]:
df_feat['lag_3'] = df_feat.groupby(['store_id','product_id'])['units_sold'].shift(3)
df_feat['lag_14'] = df_feat.groupby(['store_id','product_id'])['units_sold'].shift(14)

df_feat['roll_mean_30'] = (
    df_feat.groupby(['store_id','product_id'])['units_sold']
    .shift(1).rolling(30).mean()
)

df_feat['roll_std_14'] = (
    df_feat.groupby(['store_id','product_id'])['units_sold']
    .shift(1).rolling(14).std()
)

df_feat = df_feat.dropna().reset_index(drop=True)

In [54]:
X = df_feat.drop(columns=['units_sold','date'])
y = df_feat['units_sold']

split_index = int(len(df_feat) * 0.8)

X_train = X.iloc[:split_index]
X_test  = X.iloc[split_index:]
y_train = y.iloc[:split_index]
y_test  = y.iloc[split_index:]

In [68]:
from xgboost import XGBRegressor

model = XGBRegressor(
    n_estimators=2000,
    learning_rate=0.02,
    max_depth=10,
    min_child_weight=3,
    subsample=0.8,
    colsample_bytree=0.8,
    gamma=0.1,
    reg_alpha=1,
    reg_lambda=2,
    random_state=42,
    early_stopping_rounds=100
)
_ = model.fit(
    X_train,
    y_train,
    eval_set=[(X_test, y_test)],
    verbose=False
)
print("Model trained with early stopping ")

Model trained with early stopping

In [70]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import numpy as np

y_pred = model.predict(X_test)

print("MAE:", mean_absolute_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R2:", r2_score(y_test, y_pred))

MAE: 69.58490753173828
RMSE: 89.12327969938606
R2: 0.33644306659698486

In [72]:
model.save_model("xgb_restock_model.json")
print("Saved: xgb_restock_model.json ")

Saved: xgb_restock_model.json

In [74]:
import joblib

joblib.dump(list(X_train.columns), "model_features.pkl")

['model_features.pkl']

In [76]:
from xgboost import XGBRegressor
import joblib

m2 = XGBRegressor()
m2.load_model("xgb_restock_model.json")

features = joblib.load("model_features.pkl")

test_pred = m2.predict(X_test[features])
print("Prediction works", test_pred[:5])

Prediction works [200.9865  137.97562  84.60216 204.86597 101.39778]

In [78]:
import os
print(os.listdir())

['.ipynb_checkpoints', 'cleaned_retail_dataset_date.csv', 'clean_retail_dataset_date.csv', 'Model train.ipynb', 'model_features.pkl', 'xgb_restock_model.json']

In [80]:
from xgboost import XGBRegressor
import joblib

In [82]:
model = XGBRegressor()
model.load_model("xgb_restock_model.json")

features = joblib.load("model_features.pkl")

print("Model loaded successfully")

Model loaded successfully

In [84]:
df_feat.to_csv ("clean_retail_dataset_date.csv", index=False)
print("Saved as clean_retail_dataset_date.csv ")

Saved as clean_retail_dataset_date.csv